services:
  notification.email:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - MAIL_SMTP_STARTTLS_REQUIRED=${MAIL_SMTP_STARTTLS_REQUIRED}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - MAIL_SMTP_CONNECTIONTIMEOUT=${MAIL_SMTP_CONNECTIONTIMEOUT}
      - MAIL_SMTP_TIMEOUT=${MAIL_SMTP_TIMEOUT}
      - MAIL_SMTP_WRITETIMEOUT=${MAIL_SMTP_WRITETIMEOUT}
    volumes:
      - ./target/notifications-emails-0.0.1-SNAPSHOT.jar:/app.jar